"""KiCAD Ngspice Plotter
This program reads and plots .csv files generated by Ngspice simulation in
KiCAD.

"""

import pandas as pd
import matplotlib.pyplot as plt
from plotting import custom_plotting

# Use custom matplotlib settings
custom_plotting = custom_plotting()
# Note that with usetex=True, fonts are rendered with LaTeX. This may
# result in an error if LaTeX is not installed. In that case you can set
# usetex to False.
custom_plotting.setup_plots(fontsize=10, usetex=True)

# Import .csv from KiCAD Ngspice simulation
df = pd.read_csv('data/test.csv', sep=';')
df = df.T

# Clean the data
df.drop(df.tail(1).index, inplace=True)  # remove the default index row
new_header = df.iloc[0]  # get the first row for the header
df = df[1:]  # get the data less the header row
df.columns = new_header  # set the header row as the df header

# Convert index (Time) from string to numeric
df.index = pd.to_numeric(df.index)

# Get header labels
header = df.columns.values

# Plot each signal as a seperate trace
for trace in header:
    plt.semilogx(df.index.values, df[trace].values, label=trace)

plt.ylim(-100, 40)
plt.xlabel('Frequency (Hz)')
plt.ylabel('Gain (dB)')
plt.legend()
plt.grid(b=True, which='both')
plt.show()
